#!/usr/bin/env python3

"""Output code blocks from markdown file

For example: codeblock README.md
"""

import re
import sys
from textwrap import indent

def main(language, filename):
    if language not in ('--py', '--python'):
        raise NotImplementedError('languages other than --python not implemented')

    blocks = re.findall(r"\n```python\n(.*?)\n```", open(filename).read(), re.DOTALL)
    if not blocks:
        return
    print(
        "\n\n\n".join(
            f'def test_{i}() -> None:\n{indent(block, " " * 4)}'
            for i, block in enumerate(blocks)
        )
    )

if __name__ == '__main__':
    main(*sys.argv[1:])
