#!/usr/bin/env python3

"""Output code blocks from markdown file

For example: codeblock README.md
"""

import re
import sys
from textwrap import indent

doc = open(sys.argv[1])
blocks = re.findall(r"\n```python\n(.*?)\n```", doc.read(), re.DOTALL)
print(
    "\n\n\n".join(
        f'def test_{i}() -> None:\n{indent(block, " " * 4)}'
        for i, block in enumerate(blocks)
    )
)
